version: "3"
services:
  app:
    image: applemann/lew-static:latest
    build: .
    ports:
    - "127.0.0.1:5000:5000"
    external_links:
    - database
    environment:
    - FLASK_APP=server.py

  database:
    image: mysql:8
    ports:
    - "127.0.0.1:3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=test1
