version: "3"
services:
  app:
    image: applemann/lew-static:latest
    build: .
    ports:
    - "127.0.0.1:5000:5000"
    environment:
    - FLASK_APP=server.py
    volumes:
    - "./static:/opt/project/static"

