version: "3"
services:
  app:
    image: applemann/lew-static:1.1.0
    build: .
    ports:
    - "127.0.0.1:5000:5000"
    environment:
    - BACKEND_URL=http://localhost/api
    volumes:
    - "./static:/opt/project/static"

